version: "3.3"

services:
  web:
    build:
      context: .
    env_file:
      - .env
    ports:
      - 3000:3000
    ulimits:
      nproc: 65535
      nofile:
        soft: 100000
        hard: 100000
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: dbpassword
    ports:
      - 5432:5432
  proxy:
    image: nginx:latest
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
      - ./.next/:/next/.next/
    network_mode: "host"

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      
  proxysql:
    network_mode: "host"
    volumes:
      - "./proxysql.cnf:/etc/proxysql.cnf"
    image: proxysql/proxysql
